name: nodejs CI

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend project
        run: |
          cd frontend
          npm run build

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test